csui.define({
  toolbarButtonTitle: 'Подписать',
  dialogTitle: 'Подписать',
  signLabelSignWith: "Подписать с помощью...",
  signLabelSignersCountry: "Страна подписанта",
  signLabelPersonCode: "Персональный код",
  signLabelPersonCodeSave: "Сохранить персональный код",
  signLabelPhoneNumber: "Номер телефона",
  signLabelCountryLV: "Латвия",
  signLabelCountryLT: "Литва",
  signLabelCountryEE: "Эстония",
  signLabelMethodSmartid: "SmartID",
  signLabelMethodMobileid: "Mobile ID",
  signLabelMethodIdcard: "eID",
  xSignLabelExternalSigning: "Внешнее подписание",
  xSignButtonTitleShareDocument: "Пригласить для внутреннего подписания",
  xSignFormMsgSavingPleaseWait: "Сохранение данных, пожалуйста, подождите...",
  xSignFormLabelFirstName: "Имя",
  xSignFormPlaceholderFirstName: "Имя",
  xSignFormErrorMsgFirstName: "Пожалуйста, укажите имя подписанта",
  xSignFormLabelLastName: "Фамилия",
  xSignFormPlaceholderLastName: "Фамилия",
  xSignFormErrorMsgLastName: "Пожалуйста, укажите фамилию подписанта",
  xSignFormLabelCountry: "Страна",
  xSignFormLabelPersonCode: "Персональный код",
  xSignFormPlaceholderPersonCode: "LV:XXXXXX-XXXXX, EE:XXXXXXXXXXX, LT:XXXXXXXXXXX",
  xSignFormErrorMsgPersonCode: "Пожалуйста, укажите персональный код подписанта",
  xSignFormLabelEmail: "Э-почта",
  xSignFormPlaceholderEmail: "Э-почта",
  xSignFormErrorMsgEmail: "Пожалуйста, укажите э-почту подписанта",
  xSignFormLabelComment: "Комментарий",
  xSignFormPlaceholderComment: "Пожалуйста, укажите комментарий",
  xSignFormLabelDueDate: "Срок подписания",
  xSignFormPlaceholderDueDate: "Пожалуйста, укажите срок подписания",
  xSignFormLabelNotificationLanguage: "Язык общения",
  xSignFormButtonCancel: "Отменить приглашение",
  xSignFormButtonTitleCancel: "Данное действие отменит приглашение подписания!",
  xSignFormButtonResend: "Отослать повторно",
  xSignFormButtonTitleResend: "В течении ближайших минут подписанту будет выслано повторное приглашение!",
  xSignFormButtonShare: "Пригласить",
  xSignFormButtonClose: "Закрыть",
  createLabelContainerCreation: "Создание подписываемого контейнера",
  createLabelContainerName: "Название контейнера",
  createLabelCreateNew: "создать как новый",
  createButtonCreate: "Создать",
  createLabelInclude: "включить",
  createrLabelAddVersion: "добавить как версию",
  labelAttachments: "Приложения",
  labelSignatures: "Подписи",
  buttonDownload: "Скачать",
  buttonClose: "Закрыть",
  buttonCreate: "Создать",
  buttonCreateContainer: "Создать одписываемый контейнер",
  msgSaving: "Происходит сохранение...",
  msgSaved: "Сохранено.",
  msgSigningError: "Ошибка подписания.",
  msgSigningCancelledByUser: "Подписание отменено.",
  msgPinOk: "ПИН - правильный. Подписание завершено.",
  msgEnterPin2VerificationCode: "Введите ПИН2. Код проверки: ",
  msgSigningInProgress: "Происходит подписание...",
  msgSigningCompleted: "Подписание завершено.",
  msgPreparingData: "Происходит подготовка данных...",
  msgUnsupportedDocumentFormat: "Неподдерживаемый формат документа.",
  msgUnknownSigningMethod: "Неизвестный тип подписания.",
  msgSigningStarted: "Подписание начато...",
  msgCreationStarted: "Создание начато...",
  msgCreationCompleted: "Создание завершено.",
  msgCreationError: "Ошибка при создании."
});
