csui.define({
  toolbarButtonTitle: 'Parakstīt',
  dialogTitle: 'Parakstīt',
  signLabelSignWith: "Parakstīt ar...",
  signLabelSignersCountry: "Parakstītāja valsts",
  signLabelPersonCode: "Personas kods",
  signLabelPersonCodeSave: "Saglabāt personas kodu",
  signLabelPhoneNumber: "Telefona nr",
  signLabelCountryLV: "Latvija",
  signLabelCountryLT: "Lietuva",
  signLabelCountryEE: "Igaunija",
  signLabelMethodSmartid: "SmartID",
  signLabelMethodMobileid: "Mobile ID",
  signLabelMethodIdcard: "eID",
  xSignLabelExternalSigning: "Ārējā parakstīšana",
  xSignButtonTitleShareDocument: "Uzaicināt ārējai parakstīšanai",
  xSignFormMsgSavingPleaseWait: "Datu saglabāšana, lūdzu uzgaidīt...",
  xSignFormLabelFirstName: "Vārds",
  xSignFormPlaceholderFirstName: "Vārds",
  xSignFormErrorMsgFirstName: "Lūdzu norādiet parakstītāja vārdu",
  xSignFormLabelLastName: "Uzvārds",
  xSignFormPlaceholderLastName: "Uzvārds",
  xSignFormErrorMsgLastName: "Lūdzu norādiet parakstītāja uzvārdu",
  xSignFormLabelCountry: "Valsts",
  xSignFormLabelPersonCode: "Personas kods",
  xSignFormPlaceholderPersonCode: "LV: XXXXXX-XXXXX, EE:XXXXXXXXXXX, LT:XXXXXXXXXXX",
  xSignFormErrorMsgPersonCode: "Lūdzu norādiet parakstītāja personas kodu",
  xSignFormLabelEmail: "E-pasts",
  xSignFormPlaceholderEmail: "E-pasts",
  xSignFormErrorMsgEmail: "Lūdzu norādiet parakstītāja e-pastu",
  xSignFormLabelComment: "Komentārs",
  xSignFormPlaceholderComment: "Lūdzu norādiet komentāru",
  xSignFormLabelDueDate: "Parakstīšanas termiņš",
  xSignFormPlaceholderDueDate: "Lūdzu norādiet parakstīšanas termiņu",
  xSignFormLabelNotificationLanguage: "Saziņas valoda",
  xSignFormButtonCancel: 'Atcelt uzaicinājumu',
  xSignFormButtonTitleCancel: 'Šī darbība atcels parakstīšanas uzaicinājumu!',
  xSignFormButtonResend: "Nosūtīt atkārtoti",
  xSignFormButtonTitleResend: "Tuvāko minūšu laikā parakstītājam tiks nosūtīts atkārtots uzaicinājums!",
  xSignFormButtonShare: "Uzaicināt",
  xSignFormButtonClose: "Aizvērt",
  createLabelContainerCreation: "Parakstāmā konteinera izveide",
  createLabelContainerName: "Konteinera nosaukums",
  createLabelCreateNew: "veidot kā jaunu",
  createLabelInclude: "iekļaut",
  createrLabelAddVersion: "pievienot kā versiju",
  labelAttachments: "Pielikumi",
  labelSignatures: "Paraksti",
  buttonDownload: "Lejuplādēt",
  buttonClose: "Aizvērt",
  buttonCreate: "Izveidot",
  buttonCreateContainer: "Izveidot parakstāmu konteineri",
  msgSaving: "Notiek saglabāšana...",
  msgSaved: "Saglabāts.",
  msgSigningError: "Parakstīšanas kļūda.",
  msgSigningCancelledByUser: "Parakstīšana atcelta.",
  msgPinOk: "PIN ir pareizs. Parakstīšana pabeigta.",
  msgEnterPin2VerificationCode: "Ievadiet PIN2. Verifikācijas kods: ",
  msgSigningInProgress: "Notiek parakstīšana...",
  msgSigningCompleted: "Parakstīšana pabeigta.",
  msgPreparingData: "Notiek datu sagatavošana...",
  msgUnsupportedDocumentFormat: "Neatbalstīts dokumenta formāts.",
  msgUnknownSigningMethod: "Nezināms parakstīšanas veids.",
  msgSigningStarted: "Parakstīšana uzsākta...",
  msgCreationStarted: "Izveide uzsākta...",
  msgCreationCompleted: "Izveide pabeigta.",
  msgCreationError: "Izveides kļūda."
});