csui.define({
  toolbarButtonTitle: 'Sign',
  dialogTitle: 'Sign',
  signLabelSignWith: "Sign with...",
  signLabelSignersCountry: "Signer's country",
  signLabelPersonCode: "Person code",
  signLabelPersonCodeSave: "Save person code",
  signLabelPhoneNumber: "Phone number",
  signLabelCountryLV: "Latvia",
  signLabelCountryLT: "Lithuania",
  signLabelCountryEE: "Estonia",
  signLabelMethodSmartid: "SmartID",
  signLabelMethodMobileid: "Mobile ID",
  signLabelMethodIdcard: "ID Card",
  xSignLabelExternalSigning: "External signing",
  xSignButtonTitleShareDocument: "Share document for external signing",
  xSignFormMsgSavingPleaseWait: "Saving, please wait...",
  xSignFormLabelFirstName: "First name",
  xSignFormPlaceholderFirstName: "First name",
  xSignFormErrorMsgFirstName: "Please enter signer's first name",
  xSignFormLabelLastName: "Last name",
  xSignFormPlaceholderLastName: "Last name",
  xSignFormErrorMsgLastName: "Please enter signer's last name",
  xSignFormLabelCountry: "Country",
  xSignFormLabelPersonCode: "Person code",
  xSignFormPlaceholderPersonCode: "LV: XXXXXX-XXXXX, EE:XXXXXXXXXXX, LT:XXXXXXXXXXX",
  xSignFormErrorMsgPersonCode: "Please enter signer's person code",
  xSignFormLabelEmail: "E-mail",
  xSignFormPlaceholderEmail: "Please enter signer's e-mail",
  xSignFormErrorMsgEmail: "Please enter signer's e-mail",
  xSignFormLabelComment: "Comment",
  xSignFormPlaceholderComment: "Please enter comment",
  xSignFormLabelDueDate: "Due date",
  xSignFormPlaceholderDueDate: "Please enter due date",
  xSignFormLabelNotificationLanguage: "Notification language",
  xSignFormButtonCancel: "Cancel request",
  xSignFormButtonTitleCancel: "This will cancel the signing request!",
  xSignFormButtonResend: "Resend",
  xSignFormButtonTitleResend: "This will set the system to inform the signer again!",
  xSignFormButtonShare: "Share",
  xSignFormButtonClose: "Close",
  createLabelContainerCreation: "Container creation",
  createLabelContainerName: "Container name",
  createLabelCreateNew: "create new",
  createButtonCreate: "Create",
  createrLabelInclude: "include",
  createrLabelAddVersion: "add version",
  labelAttachments: "Attachments",
  labelSignatures: "Signatures",
  buttonDownload: "Download",
  buttonClose: "Close",
  buttonCreate: "Create",
  buttonCreateContainer: "Create signing container",
  msgSaving: "Saving...",
  msgSaved: "Saved.",
  msgSigningError: "Signing error.",
  msgSigningCancelledByUser: "Signing cancelled by user.",
  msgPinOk: "PIN OK. Signing completed.",
  msgEnterPin2VerificationCode: "Enter PIN2. Verification code: ",
  msgSigningInProgress: "Signing in progress...",
  msgSigningCompleted: "Signing completed.",
  msgPreparingData: "Preparing data...",
  msgUnsupportedDocumentFormat: "Unsupported document format.",
  msgUnknownSigningMethod: "Unknown signing method.",
  msgSigningStarted: "Signing started...",
  msgCreationStarted: "Creation started...",
  msgCreationCompleted: "Creation completed.",
  msgCreationError: "Creation error."
});